In [2]:
import numpy as np
a = np.array([[10,40],[30,20]])
print("original array:")
print(a)
print("sort the array along the first axis:")
print(np.sort(a,axis=0))
print("sort the array along the last axis:")
print(np.sort(a))
print("sort the flattered array:")
print(np.sort(a,axis=None))

original array:
[[10 40]
 [30 20]]
sort the array along the first axis:
[[10 20]
 [30 40]]
sort the array along the last axis:
[[10 40]
 [20 30]]
sort the flattered array:
[10 20 30 40]


In [5]:
import numpy as np
data_type = [('name','S15'),('class',int),('height',float)]
student_details= [('Usha',5,58.5),('saru',6,52.5)]
students=np.array(student_details,dtype=data_type)
print("original array:")
print(students)
print("sort by height")
print(np.sort(students,order='height'))
              

original array:
[(b'Usha', 5, 58.5) (b'saru', 6, 52.5)]
sort by height
[(b'saru', 6, 52.5) (b'Usha', 5, 58.5)]


In [7]:
import numpy as np
x = np.random.random(1000)
print("average of array elements:")
mean= x.mean()
print(mean)
print("standard deviation of the array elements:")
std = x.std()
print(std)
print("variance of the array elements:")
var = x.var()
print(var)

average of array elements:
0.4840416949578995
standard deviation of the array elements:
0.2866141308001372
variance of the array elements:
0.08214765997431817


In [9]:
import numpy as np
array1 = [0,1,6,1,4,1,2,2,7]
print("original array:")
print(array1)
print("number of occurences of each value in array:")
print(np.bincount(array1))

original array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
number of occurences of each value in array:
[1 3 2 0 1 0 1 1]


In [11]:
import numpy as np
n = np.arange(9).reshape(3,3)
print("original matrix:")
print(n)
result = np.trace(n)
print("Trace of matrix:")
print(result)

original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Trace of matrix:
12
